#CONFIG.YAML  Set the configuration for TMSiSAGA units to be used as "A" and "B"
#
# These header notes are split up according to the top-level fields.
#
# -- SAGA --
#  -> Currently, only supports 2 SAGA at a time.
#  -> Valid options for "Unit" property of each are:
#     - "SAGA1"
#     - "SAGA2"
#     - "SAGA3"
#     - "SAGA4"
#     - "SAGA5"
#     - "SAGAA"
#     - "SAGAB"
#
# MAKE SURE TO KEEP TRACK OF WHICH UNIT IS ASSIGNED TAG "A" AND "B"
#   -> THIS IS CRITICAL FOR KEEPING TRACK OF WHICH LEADS WENT WHERE!
#
# TO ONLY USE 1 SAGA, SET `Enable: false` ON THE CORRESPONDING UNIT.
#
# -- Default --
# The values here are mostly for initializing applications and aren't likely to be important.
#  -> THE ONE EXCEPTION IS 'Folder' -- THIS MUST BE THE ROOT LOCATION WHERE YOU WANT TO SAVE DATA.
#   -> To avoid crashing the Worker server, you should ensure that whichever machine is running Worker
#        ALSO has access to the mapped location (i.e. both computers should have "raptor" mapped).
#
# -- Network --
#
# The values under `Network` are less-likely to change (probably only if you know what you're doing).
#   -> It would be easier just to ask Max first before changing those values.

SAGA:
 A: 
   Enable: true
   Unit: "SAGAA"
   FileType: ".mat"
   Trigger:
    # Channel: 70
    Channel: 72
    Bit: 1
   Channels:
    CREF: 1
    UNI: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65]
    BIP: [66,67,68,69]
    AUX: [70,71]
    STAT: 73
    COUNT: 74
    # STAT: 71
    # COUNT: 72
    n: 
     channels: 74
     # channels: 72
     samples: 16384
 B: 
   Enable: true
   FileType: ".mat"
   Unit: "SAGAB"
   Trigger:
    Channel: 70
    Bit: 1
   Channels:
    CREF: 1
    UNI: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65]
    BIP: [66,67,68,69]
    # STAT: 70
    COUNT: 71
    STAT: 72
    n: 
     channels: 72
     samples: 16384
Default:
 # Interface: "electrical"
 Interface: "optical"
 # Folder: "R:/NMLShare/raw_data/human"
 Folder: "R:/NMLShare/raw_data/primate"
 Subject: "Test"
 Use_Worker_Server: false
 Use_Param_Server: false
 N_ICs: 20
 N_Triggers: 20
 Sample_Rate: 4000
 RMS_Sample_Epoch: 
  Start: 50
  Stop: 200
Server:
 Address:
  # TCP: "127.0.0.1"
  TCP: "128.2.244.60"
  # UDP: "127.0.0.1"
  UDP: "128.2.244.60"
 TCP:
  Controller: 5000
  A:
   Worker: 4000
   Viewer: 5020
   Parameters: 5010
  B:
   Worker: 4001
   Viewer: 5021
   Parameters: 5011
 UDP:
  state: 3030
  name: 3031
  extra: 3032
  task: 3033
  data: 3034
  recv: 3035