[config, TAG, SN, N_CLIENT] = parse_main_config(parameters('config'));

fprintf(1,'\nDeploying post-processing WORKER TCP server...\n');
cfg__worker = struct(...
    'delimiter', '.', ...
    'address', config.Server.Address.Worker, ...
    'port', config.Server.TCP.Worker, ...
    'sync_bit', config.Default.Sync_Bit, ...
    'type', config.Default.File_Type, ...
    'fcn', @callback.exportFigures, ...
    'terminator', 'LF');
serv__worker = deploy__postprocessing_worker_server(cfg__worker);
fprintf(1,'\n\n\t\t->\t[%s] Worker server is running.\t\t<-\n\n\n', string(datetime('now')));