[config, TAG, SN, N_CLIENT] = parse_main_config(parameters('config'));

fprintf(1,'Deploying post-processing WORKER TCP servers...\n');
cfg__worker = struct(...
    'delimiter', {'.'; '.'}, ...
    'tag', {'A'; 'B'}, ...
    'address', {config.Server.Address.Worker; config.Server.Address.Worker}, ...
    'port', {config.Server.TCP.A.Worker; config.Server.TCP.B.Worker}, ...
    'sync_bit', {config.SAGA.A.Trigger.Bit; config.SAGA.B.Trigger.Bit}, ...
    'type', {config.SAGA.A.FileType; config.SAGA.B.FileType}, ...
    'fcn', {@callback.exportFigures; @callback.exportFigures}, ...
    'terminator', {'LF'; 'LF'});
serv__worker = deploy__postprocessing_worker_server(cfg__worker);
fprintf(1,'complete\n');