%EXAMPLE_CONTROL_2D

fig = figure('Color','w','ToolBar','none','MenuBar','none');
ax = axes(fig,'NextPlot','add','FontName', 'Tahoma','XColor','none','YColor','none');
ylim(ax,[-10, 10]);
xlim(ax,[-10, 10]);

cursor = scatter(ax,0,0,'blue','filled','o');
cursor.UserData = struct('Calibrated', false, ...
    'Alpha', 0.2, ...
    'CalibrationData', nan(1000,2), ...
    'CalibrationIndex', 1, ...
    'UseCalibration', false, ...
    'Scale',[250, 50], ...
    'mu', zeros(1,2), ...
    'R', eye(2), ...
    'W', eye(2));
config = load_spike_server_config();

controllerClient = tcpclient(...
    config.TCP.ControlServer.Address, ...
    config.TCP.ControlServer.Port);

configureCallback(controllerClient, "terminator", ...
    @(src,evt)control_cursor_2D(src,evt,cursor));