%%
setenv("ROS_DOMAIN_ID", "42");
wristNode = ros2node("wrist");

%%
N_PTS_CURS = 180;
CURSOR_SIZE = 0.25;


fig = uifigure(...
    'Name', 'Cursor Canvas', ...
    'Color', 'k');
ax = uiaxes(fig, 'Color', 'k', ...
    'XLim', [-5 5], ...
    'YLim', [-5 5], ...
    'XColor', 'none', ...
    'YColor', 'none');
theta = linspace(0, 2*pi, N_PTS_CURS)';
cursor = patch(ax, ...
    'Faces', [1:N_PTS_CURS,1], ...
    'Vertices', [cos(theta).*CURSOR_SIZE, sin(theta).*CURSOR_SIZE], ...
    'UserData', [0, 0], ...
    'EdgeColor', 'none', ...
    'FaceColor', 'w', ...
    'DisplayName', 'cursor');
wristSub = ros2subscriber(wristNode, ...
    "wrist/pos", @(message)callback.wrist_ros2_pos_Callback(message,cursor));

%%

