function fig = init_oscope_figure(options)
%INIT_OSCOPE_FIGURE  Initialize oscilloscope figure handle for Digilent AD2
arguments
    options.ScopeChannel (1,1) {mustBeMember(options.ScopeChannel,1:2)} = 1;
    options.TimeData (1,:) double = nan;
    options.YLim (1,2) double = [0,2];
end

% Create a figure and a line handle for plotting
fig = uifigure(...
    'Color','k', ...
    'Name','AD2 Oscilloscope',...
    'Units','inches', ...
    'MenuBar','none', ...
    'ToolBar','none',...
    'Icon','outline_live_tv_black_24dp.png', ...
    'Position',[3.5, 3.5, 9.0, 5.0]);
fig.UserData.Axes = axes(fig,...
    'NextPlot','add', ...
    'FontName','Consolas', ...
    'FontSize', 16, ...
    'Color','none',...
    'XColor','w', ...
    'YColor','w',...
    'YLim',options.YLim, ...
    'HitTest','off');
yData = nan(size(options.TimeData));
fig.UserData.ScopeLine = line(fig.UserData.Axes, ...
    options.TimeData, ...
    yData, ...
    'Color', [0.85 0.85 0.85], ...
    'DisplayName', sprintf('Scope Channel-%d', options.ScopeChannel), ...
    'LineWidth', 1.25, ...
    'LineStyle', '-');
xlabel(fig.UserData.Axes,'Time (s)','Color','w','FontName','Tahoma');
ylabel(fig.UserData.Axes,'Voltage (V)','Color','w','FontName',"Tahoma");
fig.UserData.Title = title(fig.UserData.Axes,'AD2 Oscilloscope','Color','w','FontWeight','bold','FontName','Tahoma');

end