function cal = init_calibration_gui(cal, options)
%INIT_CALIBRATION_GUI  Initialize GUI for interactive calibration 
arguments
    cal
    options.FigurePosition (1,4) double = [800, 100, 720, 400];
end

if ~isempty(cal.fig)
    delete(cal.fig);
    cal.fig = [];
    cal.h = [];
end

if ~cal.enable
    return;
end

cal.fig = figure(...
    'Name', 'Calibration GUI', ...
    'Color', 'w', ...
    'Position', options.FigurePosition);

ax = axes(cal.fig,...
    'NextPlot','add', ...
    'FontName','Tahoma', ...
    'XLim',[-1 1], ...
    'YLim',[-1 1], ...
    'XTick', [], 'YTick',[],   ...
    'XColor','none','YColor','none');
cal.h = struct;
cal.h.target = plot(ax, ...
    cal.data.target_data(cal.data.current_samples,1), ...
    cal.data.target_data(cal.data.current_samples,2), ...
    'Color', [0.65 0.65 0.65], ...
    'LineWidth', 6, ...
    'MarkerIndices', cal.data.current_samples(end), ...
    'Marker', 'o', 'MarkerFaceColor',[0.4 0.4 1.0], ...
    'MarkerEdgeColor', [0.1 0.1 0.8], 'MarkerSize', 32);
cal.h.feedback = scatter(ax, ...
    cal.data.target_data(1,1), cal.data.target_data(1,2), ...
    'Marker', 'o', 'MarkerFaceColor', 'b', 'MarkerEdgeColor', 'k', 'SizeData', 64);
cal.h.title = title(ax, ...
    sprintf("Calibration GUI: %s", cal.data.control_mode), ...
    'FontName', 'Tahoma');

end