function keys = init_xbox_keys()
keys = {'up', "X", 1, 1; ...
        'down', "X", 1, 1; ...
        'left', "B", 58, 30; ...
        'right', "B", 3, 40; ...
        'a', "A", 19, 1; ...
        'b', "A", 47, 1; ...
        'x', "X", 1, 1; ...
        'y', "X", 1, 1; ...
        'l', "X", 1, 1; ...
        'r', "X", 1, 1};
end