function test__connectionFcn(src, evt)
%TEST__CONNECTIONFCN  Indicates that the connection was accepted.
assignin('base', 'connection_event', evt);
if src.Connected
    fprintf(1, ...
        "\n\nAccepted connection from client at <strong>%s:%d</strong>\n\n", evt.ClientAddress, evt.ClientPort);
    src.UserData.k = 1;
    src.UserData.figure = figure(...
        'Name', 'Test Surface', ...
        'Color', 'w', ...
        'Position', [1163 911 733 553]);
    src.UserData.axes = axes(src.UserData.figure, ...
        'ZLim', [-1.2 1.2], ...
        'CLim', [-1.0 1.0], ...
        'Box', 'on', ...
        'BoxStyle', 'full', ...
        'AmbientLightColor', 'c', ...
        'LineWidth', 1.5, ...
        'NextPlot', 'add', ...
        'View', [-15 30]);
    src.UserData.surface = surf(src.UserData.axes, src.UserData.samples);
    writeline(src, sprintf("CONNECT.%s", src.UserData.tag));
else
    disp("Client disconnected from server.");
    if isvalid(src.UserData.figure)
        delete(src.UserData.figure);
        disp("Figure closed due to client disconnect.");
    end
    src.UserData.k = -1;
end
end