function writeFittsLog(trialLogFile, trialNumber, startTime, endTime, duration, result, firstContactTime, horizontalTargetOffset, verticalTargetOffset, targetDistance, targetWidth, startTargetHoldDuration, timeToLeaveStart, controlType)
% WRITETRIALLOG Writes the trial data to a TSV file.
%
% Arguments:
%   trialLogFile - The file identifier of the open TSV file.
%   trialNumber - The trial number.
%   startTime - The start time of the trial (datetime).
%   endTime - The end time of the trial (datetime).
%   duration - The duration of the trial.
%   result - The result of the trial ('Success' or 'Failed').
%   firstContactTime - The time from target appearance to first contact.
%   horizontalTargetOffset - The x-axis offset between first and second target centers.
%   verticalTargetOffset - The y-axis offset between first and second target centers.
%   targetDistance - The distance to the target.
%   targetWidth - The width of the target.
%   startTargetHoldDuration - The required hold duration on the start target.
%   timeToLeaveStart - The duration from when the second target appears to when the subject leaves the start target.
%   controlType - enum.FittsControlType enumeration indicating the control mode used in this game.

fprintf(trialLogFile, '%d\t%s\t%s\t%.3f\t%s\t%.3f\t%d\t%d\t%d\t%d\t%.3f\t%.3f\t%d\n', ...
    trialNumber, ...
    datestr(startTime, 'HH:MM:SS.FFF'), ...
    datestr(endTime, 'HH:MM:SS.FFF'), ...
    duration, ...
    result, ...
    firstContactTime, ...
    horizontalTargetOffset, ...
    verticalTargetOffset, ...
    targetDistance, ...
    targetWidth, ...
    startTargetHoldDuration, ...
    timeToLeaveStart, ...
    int32(controlType)); %#ok<*DATST>
end
