classdef SAGA_Data_Server < handle
    %SAGA_DATA_SERVER Construct an instance of this class
    %   
    % Syntax:
    %   serv = SAGA_Data_Server('Name', value, ...);

    properties (Access = public)
        trigger_channel (1,2) double
        counter_channel (1,2) double
        sync_bit        (1,2) double
        sample_data     (136, :, :) double  % Triggered sample data for (64 UNI + 4 BIP) x 2 SAGA
        meta_data       (:, 5) double       % [x (mm), y (mm), focus (a.u.; higher is more-focused), amplitude, block]
    end

    properties (GetAccess = public, SetAccess = protected)
        subject (1,1) string = "Default"
        year    (1,1) double = year(today);
        month   (1,1) double = month(today);
        day     (1,1) double = day(today);
        block   (1,1) double = 0;

        Ready (1,1) logical = false;
        Stimulus        (1,1) double = 0;
        UIFigure        
        UITabGroup      
        UIToolbar       
        UITab = struct
        UIGrid = struct 
        UIAxes = struct
        Label = struct
        Lamp = struct       % Struct with fields that are Lamp uicontrols
        Push = struct       % Struct with fields that are PushButton uicontrols
        In = struct         % Struct with fields that are EditField or NumericEditField uicontrols
        Connection (1,1) struct = struct('Stim', [], 'Rec', [], 'Responses', []); % Has fields: "Stim" and "Rec"
    end

    properties (Hidden, Access = public)
        Queued  % Struct with queued patterns or other queued data
        prev_data
        trig_samples
        t_lim (1,2) double = [17.5, 25.0]; % Times to consider for RMS calculation
        t     (1,:) double         % Relative sample times
        n_sta (1,2) double = [0,0];    % Number of actual STA trials observed
        n_pre (1,1) double         % Number of pre-trigger samples
        n_post (1,1) double        % Number of post-trigger samples
        pattern_logger = mlog.Logger("StimPatterns");
    end

    methods % Constructor and overloaded methods
        function self = SAGA_Data_Server(varargin)
            %SAGA_DATA_SERVER Construct an instance of this class
            %   
            % Syntax:
            %   serv = SAGA_Data_Server('Name', value, ...);

            p = inputParser();
            p.addParameter('ConfigFile', parameters('config'), ...
                @(in)(isstring(in) || all(ischar(in))));
            p.addParameter('FigureIcon', 'outline_desktop_windows_black_24dp.png', ...
                @(in)(isstring(in) || all(ischar(in))))
            p.parse(varargin{:});
            config = io.yaml.loadFile(p.Results.ConfigFile, "ConvertToArray", true);
            self.subject = config.Default.Subject;
            self.trigger_channel = [config.SAGA.A.Trigger.Channel, config.SAGA.B.Trigger.Channel];
            self.counter_channel = [config.SAGA.A.Channels.COUNT, config.SAGA.B.Channels.COUNT];

            self.build_interface(config, p.Results);
            self.build_toolbar();
            self.Connection.Responses = tcpserver("0.0.0.0", config.TCP.stimulation.responses, ...
                'Timeout', 30, ...
                'ConnectionChangedFcn', @self.handle_responses_connect_disconnect);
            self.Connection.Responses.configureCallback("terminator", ...
                @self.handle_message_to_responses_server);
        end

        function delete(self)
            try %#ok<TRYNC> 
                self.UIFigure.DeleteFcn = [];
                delete(self.UIFigure);
            end

            try %#ok<TRYNC>
                delete(self.Connection.Stim);
            end

            try %#ok<TRYNC>
                delete(self.Connection.Rec);
            end

            try %#ok<TRYNC>
                delete(self.Connection.Stream.A);
            end

            try %#ok<TRYNC>
                delete(self.Connection.Stream.B);
            end

            try %#ok<TRYNC>
                delete(self.Connection.Responses);
            end
        end

        function tf = isValid(self)
            tf = isValid(self.UIFigure);
        end

        function tf = isVisible(self)
            tf = isVisible(self.UIFigure);
        end
    end % End constructor & overloaded methods

    methods (Access = public) % External functions in @SAGA_Data_Server folder
        function set_stims(self, n)
            self.Stimulus = n;
        end
        % Network message handling
        handle_acquisition_stream(self, src, ~)
        handle_message_from_stim_controller(self, src, ~)
        handle_message_from_rec_controller(self, src, ~)
        handle_message_to_responses_server(self, src, ~)
        handle_rec_connect_disconnect(self, src, ~)
        handle_responses_connect_disconnect(self, src, ~)
        handle_stim_connect_disconnect(self, src, ~)
        handle_stream_connect_disconnect(self, src, ~)
        
        % Miscellaneous utility methods
        generate_test_data(self)    % Generate random test data
        [x,y,focus] = parse_queued_pattern(self) % Parse pattern data
        save_data(self) % Saves data stored in `sample_data` and `meta_data` to a file.
    end % End external functions

    methods (Access = protected) 
        function name = tank_(self)
            name = sprintf('%s_%04d_%02d_%02d', self.subject, self.year, self.month, self.day);
        end

        function name = block_(self)
            name = sprintf('%s_%d', self.tank_(), self.block);
        end

        function handle_buffer_parameter_changed(self, ~, ~)
            self.Lamp.Init.Color = [0.1 0.1 0.9];
            self.Ready = false;
        end

        function handle_save_push(self, ~, ~)
            %HANDLE_SAVE_PUSH  Open save dialog for saving `meta_data` and `sample_data`
            self.save_data();
        end

        function handle_sync_bit_changed(self, src, ~)
            %HANDLE_SYNC_BIT_CHANGED  Set sync bit for both SAGA devices.
            self.sync_bit = ones(1,2) .* src.Value;
        end

        function handle_init_push(self, ~, ~)
            %HANDLE_INIT_PUSH  Pushbutton callback for "Init" button
            if ~self.Ready
                self.n_pre = self.In.N_Pre.Value;
                self.n_post = self.In.N_Post.Value;
                self.t = (-self.n_pre / 4) : 0.25 : (self.n_post / 4);
                nTrials = self.In.N_Max_Trials.Value;
                self.sample_data = nan(136, ...             % 64 UNI + 4 BIP x 2 SAGA
                    1 + self.n_pre + self.n_post, ...     % Time samples
                    nTrials);                               % Maximum allowed trials
                self.meta_data = nan(nTrials, 5); % [x (mm), y (mm), focusing (a.u.), amplitude, block]
                self.Stimulus = 0; % Indexing for the TCP hand-shaking part
                self.n_sta = [0,0]; % Indexing for graphics and other "online" database tracking part
            end
            self.In.N_Pre.Enable = 'off';
            self.In.N_Post.Enable = 'off';
            self.In.N_Max_Trials.Enable = 'off';
            self.Push.Unlock_Init.Enable = 'on';
            self.Push.Init.Enable = 'off'; 
            
            self.Lamp.Init.Color = [0.1 0.9 0.1];
            self.Ready = true;
        end

        function handle_temporal_refresh_push(self, ~, ~)
            %HANDLE_TEMPORAL_REFRESH_PUSH  Pushbutton callback for "Refresh" button
            delete(self.UIAxes.Temporal.Children);
            bk = self.In.Block.Value;
            ch = self.In.Channel.Value;
            idx = self.meta_data(:,5) == bk;
            n = sum(idx);
            if n < 1
                y = nan(size(self.t));
                cdata = [0.9, 0.1, 0.1];
            elseif sum(idx) == 1
                y = self.sample_data(ch,:,idx);
                cdata = [0.0, 0.0, 0.0];
            else
                y = squeeze(self.sample_data(ch,:,idx));
                cdata = [0.0, 0.0, 0.0];
            end
            plot(self.UIAxes.Temporal, self.t, y);
            [tag, chname] = SAGA_Data_Server.channel_index_2_name(ch);
            set(self.Label.Temporal, ...
                'String', sprintf('Block-%d | %s | %s (n = %d)', bk, tag, chname, n), ...
                'Color', cdata);
            drawnow();
        end

        function handle_spatial_refresh_push(self, ~, ~)
            %HANDLE_SPATIAL_REFRESH_PUSH  Pushbutton callback for "Refresh" button
            delete(self.UIAxes.Spatial.Children);
            bk = self.In.Block.Value;
            ch = self.In.Channel.Value;
            amp = self.In.Amplitude.Value;
            idx = (self.meta_data(:,5) == bk) & (self.meta_data(:,4) == amp);
            n = sum(idx);

            [tag, chname] = SAGA_Data_Server.channel_index_2_name(ch);
            set(self.Label.Spatial, ...
                'String', sprintf('Block-%d | %s | %s (n = %d)', bk, tag, chname, n));
            
            if n < 1
                return;
            elseif sum(idx) == 1
                z = self.sample_data(ch,:,idx);
            else
                z = squeeze(self.sample_data(ch,:,idx))';
            end
            t_idx = (self.t >= self.t_lim(1)) & (self.t <= self.t_lim(2));
            z = rms(z(:, t_idx), 2);
            x = self.meta_data(idx,1);
            y = self.meta_data(idx,2);
            bubblechart(self.UIAxes.Spatial, x, y, z);
            drawnow();
        end

        function handle_spatial_imit_change(self, ~, ~)
            %HANDLE_SPATIAL_LIMIT_CHANGE  Handles chaning spatial-axes limits
            set(self.UIAxes.Spatial, ...
                'XLim', [self.In.XMin.Value, self.In.XMax.Value], ... 
                'YLim', [self.In.YMin.Value, self.In.YMax.Value])
        end
    
        function handle_unlock_push(self, ~, ~)
            %HANDLE_UNLOCK_PUSH  Pushbutton callback for "Unlock" button
            self.Push.Init.Enable = 'on';
            self.In.N_Pre.Enable = 'on';
            self.In.N_Post.Enable = 'on';
            self.In.N_Max_Trials.Enable = 'on';
            self.Push.Unlock_Init.Enable = 'off';
        end

        function update_experiment_text(self, varargin)
            %UPDATE_EXPERIMENT_TEXT  Updates the text in self.Label.Experiment
            p = inputParser();
            p.addParameter('subject', self.subject);
            p.addParameter('year', self.year);
            p.addParameter('month', self.month);
            p.addParameter('day', self.day);
            p.addParameter('block', self.block);
            p.parse(varargin{:});
            self.subject = p.Results.subject;
            self.year = p.Results.year;
            self.month = p.Results.month;
            self.day = p.Results.day;
            self.block = p.Results.block;
            self.In.Block.Value = self.block;
            self.Label.Experiment.Text =  sprintf('%s: %04d-%02d-%02d (%d)', ...
                p.Results.subject, p.Results.year, p.Results.month, p.Results.day, p.Results.block);
        end

        % Gigantic function that builds the UI elements
        function build_interface(self, config, parameters)
            %BUILD_INTERFACE  Make all the stuff
            switch getenv("COMPUTERNAME")
                case 'NMLNHP-DELL-C01'
                    pos = [1234 291 667 420];
                otherwise
                    pos = [260 1398 667 420];
            end
            self.UIFigure = uifigure(...
                'Name', 'TMSi SAGA Data Server', ...
                'Color', 'w', ...
                'Icon', parameters.FigureIcon, ...
                'Position', pos, ...
                'DeleteFcn', @(~,~)self.delete);
            maingrid = uigridlayout(self.UIFigure, ...
                'ColumnWidth', {'1x', '20x', '1x'}, ...
                'RowHeight', {'1x', '20x', '1x'}, ...
                'BackgroundColor', [0 0 0]);
            self.Label.Experiment = uilabel(maingrid, ...
                'FontName', 'Tahoma', 'FontSize', 14, 'FontWeight', 'bold', ...
                'Text', 'Not Connected', 'HorizontalAlignment', 'left', ...
                'FontColor', [1 1 1]);
            self.Label.Experiment.Layout.Row = 1;
            self.Label.Experiment.Layout.Column = [1 2];
            self.Lamp.Responses = uilamp(maingrid, 'Color', [0.1 0.1 0.9]);
            self.Lamp.Responses.Layout.Row = 1;
            self.Lamp.Responses.Layout.Column = 3;

            self.UITabGroup = uitabgroup(maingrid);
            self.UITabGroup.Layout.Row = [2 3];
            self.UITabGroup.Layout.Column = [1 3];
            self.UITab.Controls = uitab(self.UITabGroup, ...
                'Title', 'Controls');
            self.UIGrid.Controls = uigridlayout(self.UITab.Controls, ...
                'ColumnWidth', {'1x', '1x', '1x'}, ...
                'RowHeight', {'1x', '1x', '1x', '1x'}, ...
                'BackgroundColor', [1 1 1]);

            % % Interface part for pre-allocating triggered data buffer % %
            self.Lamp.Init = uilamp(self.UIGrid.Controls, ...
                'Color', [0.9 0.9 0.9]);
            self.Lamp.Init.Layout.Row = 1;
            self.Lamp.Init.Layout.Column = 1;

            self.Push.Init = uibutton(self.UIGrid.Controls, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Re-allocate stim-triggered data tensor.'}, ...
                'Enable', 'on', ...
                'Text', 'Init', 'ButtonPushedFcn', @self.handle_init_push);
            self.Push.Init.Layout.Row = 2;
            self.Push.Init.Layout.Column = 1;

            self.Push.Unlock_Init = uibutton(self.UIGrid.Controls, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Unlocks the Init button.'}, ...
                'Enable', 'off', ...
                'Text', 'Unlock', 'ButtonPushedFcn', @self.handle_unlock_push);
            self.Push.Unlock_Init.Layout.Row = 3;
            self.Push.Unlock_Init.Layout.Column = 1;

            lab = uilabel(self.UIGrid.Controls, ...
                'FontName', 'Tahoma', 'FontSize', 14, ...
                'Text', 'Sync Bit', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 1;
            lab.Layout.Column = 2;

            self.In.Sync_Bit = uieditfield(self.UIGrid.Controls, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', true, ...
                'FontSize', 14, ...
                'Limits', [0, 15], ...
                'ValueChangedFcn', @self.handle_sync_bit_changed, ...
                'Value', config.SAGA.A.Trigger.Bit);
            self.sync_bit = ones(1,2).*config.SAGA.A.Trigger.Bit;
            self.In.Sync_Bit.Layout.Row = 1;
            self.In.Sync_Bit.Layout.Column = 3;

            lab = uilabel(self.UIGrid.Controls, ...
                'FontName', 'Tahoma', 'FontSize', 14, ...
                'Text', 'Pre-Trigger Samples', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 2;

            self.In.N_Pre = uieditfield(self.UIGrid.Controls, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', false, ...
                'FontSize', 14, ...
                'Limits', [0, 80], ...
                'ValueChangedFcn', @self.handle_buffer_parameter_changed, ...
                'Value', config.Default.N_Pre);
            self.n_pre = config.Default.N_Pre;
            self.In.N_Pre.Layout.Row = 2;
            self.In.N_Pre.Layout.Column = 3;

            lab = uilabel(self.UIGrid.Controls, ...
                'FontName', 'Tahoma', 'FontSize', 14, ...
                'Text', 'Post-Trigger Samples', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 3;
            lab.Layout.Column = 2;

            self.In.N_Post = uieditfield(self.UIGrid.Controls, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', false, ...
                'FontSize', 14, ...
                'Limits', [0, 200], ...
                'ValueChangedFcn', @self.handle_buffer_parameter_changed, ...
                'Value', config.Default.N_Post);
            self.n_post = config.Default.N_Post;
            self.In.N_Post.Layout.Row = 3;
            self.In.N_Post.Layout.Column = 3;

            lab = uilabel(self.UIGrid.Controls, ...
                'FontName', 'Tahoma', 'FontSize', 12, ...
                'Text', 'Max Buffered Trials', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 4;
            lab.Layout.Column = 2;

            self.In.N_Max_Trials = uieditfield(self.UIGrid.Controls, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', true, ...
                'ValueDisplayFormat', '%6d', ...
                'FontSize', 14, ...
                'Limits', [1, 60000], ...
                'ValueChangedFcn', @self.handle_buffer_parameter_changed, ...
                'Value', config.Default.N_Max_Trials);
            self.In.N_Max_Trials.Layout.Row = 4;
            self.In.N_Max_Trials.Layout.Column = 3;

            % % Build the tab for "Stimulation Handshake" connections % %
            self.UITab.StimConnections = uitab(self.UITabGroup, ...
                'Title', 'Stim Handshake Connections');
            self.UIGrid.StimConnections = uigridlayout(self.UITab.StimConnections, ...
                'ColumnWidth', {'2x', '3x', '1x', '1x'}, ...
                'RowHeight', {'1x', '1x', '1x', '1x'}, ...
                'BackgroundColor', [1 1 1]);

            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Stim Server IP', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 1;
            lab.Layout.Column = 1;

            self.In.StimServerHost = uieditfield(self.UIGrid.StimConnections, 'text', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Placeholder', 'A.B.C.D', ...
                'Value', config.Host.stimulation.server);
            self.In.StimServerHost.Layout.Row = 1;
            self.In.StimServerHost.Layout.Column = 2;

            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Stim Port', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 1;

            self.In.StimServerPort = uieditfield(self.UIGrid.StimConnections, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Limits', [1, 100000], ...
                'Value', config.TCP.stimulation.server);
            self.In.StimServerPort.Layout.Row = 2;
            self.In.StimServerPort.Layout.Column = 2;

            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 13, ...
                'Text', 'Connected', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 1;
            lab.Layout.Column = 3;

            self.Lamp.StimServer = uilamp(self.UIGrid.StimConnections, ...
                'Color', [0.9 0.9 0.9]);
            self.Lamp.StimServer.Layout.Row = 1;
            self.Lamp.StimServer.Layout.Column = 4;

            self.Push.Connect_Stim = uibutton(self.UIGrid.StimConnections, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Connect via TCP with stimulation controller server.'}, ...
                'Text', 'Connect', 'ButtonPushedFcn', @self.handle_stim_connect_disconnect);
            self.Push.Connect_Stim.Layout.Row = 2;
            self.Push.Connect_Stim.Layout.Column = [3 4];

            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Rec Server IP', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 3;
            lab.Layout.Column = 1;

            self.In.TMSiServerHost = uieditfield(self.UIGrid.StimConnections, 'text', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Placeholder', 'A.B.C.D', ...
                'Value', config.Host.interface);
            self.In.TMSiServerHost.Layout.Row = 3;
            self.In.TMSiServerHost.Layout.Column = 2;

            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Rec Port', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 4;
            lab.Layout.Column = 1;

            self.In.TMSiServerPort = uieditfield(self.UIGrid.StimConnections, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Limits', [1, 100000], ...
                'Value', config.TCP.tmsi.server);
            self.In.TMSiServerPort.Layout.Row = 4;
            self.In.TMSiServerPort.Layout.Column = 2;
            
            lab = uilabel(self.UIGrid.StimConnections, ...
                'FontName', 'Tahoma', 'FontSize', 13, ...
                'Text', 'Connected', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 3;
            lab.Layout.Column = 3;

            self.Lamp.TMSiServer = uilamp(self.UIGrid.StimConnections, ...
                'Color', [0.9 0.9 0.9]);
            self.Lamp.TMSiServer.Layout.Row = 3;
            self.Lamp.TMSiServer.Layout.Column = 4;

            self.Push.Connect_Rec = uibutton(self.UIGrid.StimConnections, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Connect via UDP with stimulation controller server.'}, ...
                'Text', 'Connect', 'ButtonPushedFcn', @self.handle_rec_connect_disconnect);
            self.Push.Connect_Rec.Layout.Row = 4;
            self.Push.Connect_Rec.Layout.Column = [3 4];

            % % Build the tab for TMSi Recording Stream connections % %
            self.UITab.RecConnections = uitab(self.UITabGroup, ...
                'Title', 'Recording Connections');
            self.UIGrid.RecConnections = uigridlayout(self.UITab.RecConnections, ...
                'ColumnWidth', {'2x', '3x', '2x', '1x'}, ...
                'RowHeight', {'1x', '1x', '1x'}, ...
                'BackgroundColor', [1 1 1]);

            lab = uilabel(self.UIGrid.RecConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'SAGA Host', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 1;
            lab.Layout.Column = 1;

            self.In.StreamHost = uieditfield(self.UIGrid.RecConnections, 'text', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Placeholder', 'A.B.C.D', ...
                'Value', config.Host.streams);
            self.In.StreamHost.Layout.Row = 1;
            self.In.StreamHost.Layout.Column = 2:3;

            lab = uilabel(self.UIGrid.RecConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'SAGA A Port', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 1;

            self.In.StreamPort.A = uieditfield(self.UIGrid.RecConnections, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Limits', [1, 100000], ...
                'Value', config.TCP.tmsi.streams.A);
            self.In.StreamPort.A.Layout.Row = 2;
            self.In.StreamPort.A.Layout.Column = 2;

            self.Push.Connect_Stream.A = uibutton(self.UIGrid.RecConnections, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Connect via TCP with SAGA-A stream.'}, ...
                'UserData', struct('tag', "A", 'saga', 1), ...
                'Text', 'Connect', 'ButtonPushedFcn', @self.handle_stream_connect_disconnect);
            self.Push.Connect_Stream.A.Layout.Row = 2;
            self.Push.Connect_Stream.A.Layout.Column = 3;

            self.Lamp.Stream.A = uilamp(self.UIGrid.RecConnections, ...
                'Color', [0.9 0.9 0.9]);
            self.Lamp.Stream.A.Layout.Row = 2;
            self.Lamp.Stream.A.Layout.Column = 4;

            lab = uilabel(self.UIGrid.RecConnections, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'SAGA B Port', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 3;
            lab.Layout.Column = 1;

            self.In.StreamPort.B = uieditfield(self.UIGrid.RecConnections, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'FontSize', 16, ...
                'Limits', [1, 100000], ...
                'Value', config.TCP.tmsi.streams.B);
            self.In.StreamPort.B.Layout.Row = 3;
            self.In.StreamPort.B.Layout.Column = 2;

            self.Push.Connect_Stream.B = uibutton(self.UIGrid.RecConnections, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Connect via TCP with SAGA-B stream.'}, ...
                'UserData', struct('tag', "B", 'saga', 2), ...
                'Text', 'Connect', 'ButtonPushedFcn', @self.handle_stream_connect_disconnect);
            self.Push.Connect_Stream.B.Layout.Row = 3;
            self.Push.Connect_Stream.B.Layout.Column = 3;

            self.Lamp.Stream.B = uilamp(self.UIGrid.RecConnections, ...
                'Color', [0.9 0.9 0.9]);
            self.Lamp.Stream.B.Layout.Row = 3;
            self.Lamp.Stream.B.Layout.Column = 4;
            
            % % Build the tab for data visualization % %
            self.UITab.Temporal = uitab(self.UITabGroup, ...
                'Title', 'Temporal Data');
            self.UIGrid.Temporal = uigridlayout(self.UITab.Temporal, ...
                'ColumnWidth', {'1x', '2x', '1x', '2x', '2x', '1x'}, ...
                'RowHeight', {'8x', '1x'}, ...
                'BackgroundColor', [1 1 1]);
            self.UIAxes.Temporal = uiaxes(self.UIGrid.Temporal, ...
                'FontName', 'Tahoma', 'NextPlot', 'add');
            xlabel(self.UIAxes.Temporal, 'Time (ms)', 'FontName', 'Tahoma', 'Color', 'k');
            ylabel(self.UIAxes.Temporal, 'Amplitude (mV)', 'FontName', 'Tahoma', 'Color', 'k');
            self.Label.Temporal = title(self.UIAxes.Temporal, 'Block-0 | A | UNI-01', 'FontName', 'Tahoma', 'Color', 'k');
            self.UIAxes.Temporal.Layout.Row = 1;
            self.UIAxes.Temporal.Layout.Column = [2 5];
            self.UIAxes.Temporal.Toolbar.Visible = 'off';
            self.UIAxes.Temporal.Interactions = [panInteraction zoomInteraction];
            
            lab = uilabel(self.UIGrid.Temporal, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Block', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 1;

            self.In.Block = uieditfield(self.UIGrid.Temporal, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', true, ...
                'FontSize', 16, ...
                'Limits', [0, 100000], ...
                'Value', 0);
            self.In.Block.Layout.Row = 2;
            self.In.Block.Layout.Column = 2;

            lab = uilabel(self.UIGrid.Temporal, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Channel', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 3;

            self.In.Channel = uieditfield(self.UIGrid.Temporal, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'RoundFractionalValues', true, ...
                'FontSize', 16, ...
                'Limits', [1, 136], ...
                'Value', 1);
            self.In.Channel.Layout.Row = 2;
            self.In.Channel.Layout.Column = 4;

            self.Push.Refresh_Temporal = uibutton(self.UIGrid.Temporal, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Refresh the data plot.'}, ...
                'Text', 'Refresh', 'ButtonPushedFcn', @self.handle_temporal_refresh_push);
            self.Push.Refresh_Temporal.Layout.Row = 2;
            self.Push.Refresh_Temporal.Layout.Column = 5;

             % % Build the tab for sweep visualization % %
            self.UITab.Spatial = uitab(self.UITabGroup, ...
                'Title', 'Spatial Data');
            self.UIGrid.Spatial = uigridlayout(self.UITab.Spatial, ...
                'ColumnWidth', {'1x', '2x', '2x', '1x', '2x', '2x', '1x', '2x', '3x', '1x'}, ...
                'RowHeight', {'8x', '1x'}, ...
                'BackgroundColor', [1 1 1]);
            self.UIAxes.Spatial = uiaxes(self.UIGrid.Spatial, ...
                'FontName', 'Tahoma', 'NextPlot', 'add', ...
                'XLimMode', 'manual', 'XLim', [-6.5, 6.5], ...
                'YLimMode', 'manual', 'YLim', [-2.5, 2.5]);
            xlabel(self.UIAxes.Spatial, 'ML (mm)', 'FontName', 'Tahoma', 'Color', 'k');
            ylabel(self.UIAxes.Spatial, 'AP (mm)', 'FontName', 'Tahoma', 'Color', 'k');
            self.Label.Spatial = title(self.UIAxes.Spatial, 'Block-0 | A | UNI-01', 'FontName', 'Tahoma', 'Color', 'k');
            self.UIAxes.Spatial.Layout.Row = 1;
            self.UIAxes.Spatial.Layout.Column = [2 9];
            self.UIAxes.Spatial.Toolbar.Visible = 'off';
            self.UIAxes.Spatial.Interactions = [panInteraction zoomInteraction];
            
            lab = uilabel(self.UIGrid.Spatial, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'X', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 1;

            self.In.XMin = uieditfield(self.UIGrid.Spatial, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'Tooltip', {'Min X-Grid (mm)'}, ...
                'RoundFractionalValues', false, ...
                'FontSize', 16, ...
                'Limits', [-100000, 100000], ...
                'Value', -6.5, ...
                'ValueChangedFcn', @self.handle_spatial_limit_change);
            self.In.XMin.Layout.Row = 2;
            self.In.XMin.Layout.Column = 2;

            self.In.XMax = uieditfield(self.UIGrid.Spatial, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'Tooltip', {'Max X-Grid (mm)'}, ...
                'RoundFractionalValues', false, ...
                'FontSize', 16, ...
                'Limits', [-100000, 100000], ...
                'Value', 6.5, ...
                'ValueChangedFcn', @self.handle_spatial_limit_change);
            self.In.XMax.Layout.Row = 2;
            self.In.XMax.Layout.Column = 3;

            lab = uilabel(self.UIGrid.Spatial, ...
                'FontName', 'Tahoma', 'FontSize', 16, ...
                'Text', 'Y', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 4;

            self.In.YMin = uieditfield(self.UIGrid.Spatial, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'Tooltip', {'Min Y-Grid (mm)'}, ...
                'RoundFractionalValues', false, ...
                'FontSize', 16, ...
                'Limits', [-100000, 100000], ...
                'Value', -2.5, ...
                'ValueChangedFcn', @self.handle_spatial_limit_change);
            self.In.YMin.Layout.Row = 2;
            self.In.YMin.Layout.Column = 5;

            self.In.YMax = uieditfield(self.UIGrid.Spatial, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'Tooltip', {'Max Y-Grid (mm)'}, ...
                'RoundFractionalValues', false, ...
                'FontSize', 16, ...
                'Limits', [-100000, 100000], ...
                'Value', 2.5, ...
                'ValueChangedFcn', @self.handle_spatial_limit_change);
            self.In.YMax.Layout.Row = 2;
            self.In.YMax.Layout.Column = 6;

            lab = uilabel(self.UIGrid.Spatial, ...
                'FontName', 'Tahoma', 'FontSize', 12, ...
                'Text', 'Amp', ...
                'HorizontalAlignment', 'right');
            lab.Layout.Row = 2;
            lab.Layout.Column = 7;

            self.In.Amplitude = uieditfield(self.UIGrid.Spatial, 'numeric', ...
                'HorizontalAlignment', 'center', ...
                'FontName', 'Tahoma', ...
                'Tooltip', {'Stimulation Amplitude'}, ...
                'RoundFractionalValues', false, ...
                'FontSize', 16, ...
                'Limits', [-100000, 100000], ...
                'Value', 0);
            self.In.Amplitude.Layout.Row = 2;
            self.In.Amplitude.Layout.Column = 8;

            self.Push.Refresh_Spatial = uibutton(self.UIGrid.Spatial, 'push', ...
                'FontName', 'Tahoma', 'FontSize', 20, ...
                'Tooltip', {'Refresh the data plot.'}, ...
                'Text', 'Refresh', 'ButtonPushedFcn', @self.handle_spatial_refresh_push);
            self.Push.Refresh_Spatial.Layout.Row = 2;
            self.Push.Refresh_Spatial.Layout.Column = 9;
        end
    
        function build_toolbar(self)
            %BUILD_TOOLBAR  Smaller function to build just the toolbar
            self.UIToolbar = uitoolbar(self.UIFigure);

            % Create SavePushTool
            self.Push.Save = uipushtool(self.UIToolbar, ...
                'Tooltip', {'Open data-saving dialog.'}, ...
                'ClickedCallback', @self.handle_save_push, ...
                'Icon', 'baseline_save_black_24dp.png');
        end
    end

    methods (Static, Access = public) % External static functions in @SAGA_Data_Server folder
        [tag, chname] = channel_index_2_name(ch)           % Parses the string representation of SAGA (tag) and channel name given channel index and assuming fixed indexing scheme
        pdata = parse_pattern_volume_string(str, varargin) % Parses pattern volume string from filenames.
    end
end